### ISSUE TITLE
Error while installing ukfast/safedns v1.1.3: checksum list has no SHA-256 hash

### ISSUE THREAD

**Issue by djalertive** [ukfast/terraform-provider-safedns#5]
When running terraform init the ukfast/safedns v1.1.3 plugin is failing to install with the following error:

> Error: Failed to install provider
> 
> Error while installing ukfast/safedns v1.1.3: checksum list has no SHA-256
> hash for
> "https://github.com/ans-group/terraform-provider-safedns/releases/download/v1.1.3/terraform-provider-safedns_1.1.3_linux_amd64.zip"

**Comment by 0x4c6565** [comment]
Hi @djalertive,

Apologies, only just seeing this. This is (unintentionally) due to the organisation changing from `ukfast` to `ans-group`. You will need to update your provider configuration to reference the `ans-group` organisation instead:

https://github.com/ans-group/terraform-provider-safedns/blob/master/README.md#upgrading
